version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my-flask-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" 
  redis:
      image: redis:latest
      ports:
        - "6379:6379" 
  web:
    build: .
    ports:
      - "8080:8080" 
    depends_on:
      - db
      - redis
  