version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: platform_nginx
    restart: always
    volumes:
        - ./nginx:/etc/nginx/conf.d
    ports:
        - 80:80
        - 443:443
    networks:
        - backend
        - frontend

  db:
    image: postgres:latest
    container_name: platform_postgres
    restart: always
    environment:
      POSTGRES_DB: my-flask-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432 
    networks:
      - backend

  redis:
      image: redis:latest
      container_name: platform_redis      
      restart: always
      ports:
        - 6379:6379 
      networks:
        - backend

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    restart: always
    container_name: platform_api
    ports:
      - 6700:6700 
    depends_on:
      - db
      - redis
    networks:
      - backend
  
  web:
    build:
        context: ./web
        dockerfile: Dockerfile
    container_name: platform_web
    restart: always
    volumes:
        - ./web/app:/app
    ports:
        - 3000:3000
    depends_on:
        - api
    networks:
      - frontend
networks:
  backend:
  frontend: