version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my-flask-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" 
  redis:
      image: redis:latest
      ports:
        - "6379:6379" 
  web:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    depends_on:
      - db
      - redis
  