version: '3'

services:
  web:
    build:
        context: ./web
        dockerfile: Dockerfile
    container_name: platform_web
    restart: always
    ports:
      - 3000
    depends_on:
        - api
    networks:
      - frontend
  api:
    platform: linux/amd64
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: platform_api
    restart: always
    ports:
      - 6700
    depends_on:
      - db
      - redis
    networks:
      - backend
  
  nginx:
    image: nginx:latest
    container_name: platform_nginx
    restart: always
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./nginx:/etc/nginx/conf.d
    networks:
        - backend
        - frontend

  db:
    image: postgres:latest
    container_name: platform_postgres
    restart: always
    ports:
      - 5432
    environment:
      POSTGRES_DB: my-flask-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: platform_redis      
    restart: always
    ports:
      - 6379
    volumes:
      - rdata:/data
    networks:
      - backend
networks:
  backend:
  frontend:
volumes:
  pgdata:
  rdata:
